# Generated by Django 4.2.4 on 2023-09-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_deleted_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
