# Generated by Django 4.2.4 on 2023-09-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
