# Generated by Django 4.2.4 on 2023-09-26 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_deleted_at_sms_created_at_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
