# Generated by Django 4.2.4 on 2023-09-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_sms_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sms',
            new_name='AuthSms',
        ),
    ]
