# Generated by Django 4.2.4 on 2023-09-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_sms_authsms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authsms',
            options={'verbose_name': 'Auth Sms', 'verbose_name_plural': 'Auth Sms'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
