# Generated by Django 4.2.4 on 2023-09-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_authsms_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsms',
            name='secure_code',
            field=models.CharField(max_length=6),
        ),
    ]
