# Generated by Django 4.2.4 on 2023-09-27 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_authsms_secure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsms',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authsms', to=settings.AUTH_USER_MODEL),
        ),
    ]
