version: '3.3'

services:
  web:
    restart: always
    container_name: django
    build: .
    # build:
    #   context: ./app
    #   dockerfile: Dockerfile
    command: 
      - gunicorn imodels.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
       - media:/usr/src/app/media
      #  - static:/usr/src/app/staticfiles/

  db:
    restart: always
    image: postgres:15-alpine
    container_name: db
    # environment:
    #   - POSTGRES_DB=Imodels
    #   - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=123
    ports:
      - "5430:5432"
    depends_on:
      - web
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  nginx:
    build: ./nginx
    volumes:
      # - static_volume:/home/app/web/staticfiles
      - media:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

  # pgadmin:
  #     restart: always
  #     image: dpage/pgadmin4:latest
  #     container_name: pgadmin
  #     depends_on:
  #       - pgdb
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: jobirumirovmoliya@gmail.com
  #       PGADMIN_DEFAULT_PASSWORD: pgadmin
  #     ports:
  #       - "8080:80"

volumes:
  postgres_data:
  data:
  media:
  # static:

