version: '3.3'

services:
  web:
    restart: always
    container_name: web
    build: .
    command: 
      - gunicorn 
      - imodels.wsgi:application 
      - --bind
      - 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./mediafiles:/usr/src/app/mediafiles

  db:
    restart: always
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: Imodels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  nginx:
    restart: unless-stopped
    image: nginx
    container_name: web_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/usr/src/app/staticfiles
      - ./mediafiles:/usr/src/app/mediafiles
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data: