version: '3.3'

services:
  web:
    restart: always
    container_name: django
    build: .
    command: 
      - gunicorn 
      - imodels.wsgi:application 
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
       - media:/usr/src/app/media
      #  - static:/usr/src/app/staticfiles/

  db:
    restart: always
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5430:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  nginx:
    build: ./nginx
    volumes:
      # - static_volume:/home/app/web/staticfiles
      - media:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  media:
  # static:

