FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

WORKDIR /usr/src/app
COPY requirements.txt ./
COPY . . 

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN chmod +x entrypoint.sh


COPY entrypoint.sh .
ENTRYPOINT ["sh", "entrypoint.prod.sh"]
