# Generated by Django 4.2.4 on 2023-09-02 11:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
