# Generated by Django 4.2.4 on 2023-09-14 17:08

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productvideo_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video_link',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
