# Generated by Django 4.2.4 on 2023-09-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderproduct_orderproductitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
