# Generated by Django 4.2.4 on 2023-12-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_type_name_en_type_name_ru_type_name_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
