# Generated by Django 4.2.4 on 2023-08-10 12:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kk',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_kk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
