# Generated by Django 4.2.4 on 2023-09-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='related_configurator',
            new_name='related_product',
        ),
    ]
