# Generated by Django 4.2.4 on 2023-09-03 14:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='text_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='text_uz',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='extradescription',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extradescription',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extradescription',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
