# Generated by Django 4.2.4 on 2023-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='description',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
