# Generated by Django 4.2.4 on 2023-09-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_related_configurator_product_related_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatureoption',
            name='feature_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureoption',
            name='feature_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productfeatureoption',
            name='feature_uz',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
