# Generated by Django 4.2.4 on 2023-09-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproductitem',
            old_name='order_conf',
            new_name='order_product',
        ),
    ]
