# Generated by Django 4.2.4 on 2023-09-03 18:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_description_text_en_description_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=500)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
