# Generated by Django 4.2.4 on 2023-09-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_orderitem_orderconfigurator'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfigurator',
            name='configurator_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.configuratorproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderconfigurator',
            name='configurator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.configurator'),
        ),
    ]
