# Generated by Django 4.2.4 on 2023-09-21 03:37

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_order_conf_orderproductitem_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[shop.validators.validate_phone_length]),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default=998977366898, max_length=12, validators=[shop.validators.validate_phone_length]),
            preserve_default=False,
        ),
    ]
