# Generated by Django 4.2.4 on 2023-12-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
