# Generated by Django 4.2.4 on 2023-10-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_description_text_alter_description_text_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_en',
            new_name='information_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_ru',
            new_name='information_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_uz',
            new_name='information_uz',
        ),
        migrations.RenameField(
            model_name='productvideo',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='productvideo',
            old_name='description_en',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='productvideo',
            old_name='description_uz',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='productvideo',
            old_name='description_ru',
            new_name='text_uz',
        ),
    ]
