# Generated by Django 4.2.4 on 2023-09-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_blog_text_en_blog_text_ru_blog_text_uz_blog_title_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='preview_image',
        ),
    ]
