# Generated by Django 4.2.4 on 2023-10-08 11:20

from django.db import migrations, models
import django.db.models.deletion
import shop.models.description


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_description_product_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.description.product_extradesc_image_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_uz', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='extradescription',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': "Qo'shimcha tavsif", 'verbose_name_plural': "Qo'shimcha tavsiflar"},
        ),
        migrations.RemoveField(
            model_name='description',
            name='extradescription',
        ),
        migrations.RemoveField(
            model_name='description',
            name='text',
        ),
        migrations.RemoveField(
            model_name='description',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='description',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='description',
            name='text_uz',
        ),
        migrations.AddField(
            model_name='description',
            name='product',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='product_description', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='title_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ExtraDescImage',
        ),
        migrations.DeleteModel(
            name='ExtraDescription',
        ),
        migrations.AddField(
            model_name='descriptionpoint',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_points', to='shop.description'),
        ),
        migrations.AddField(
            model_name='descriptionimage',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_images', to='shop.description'),
        ),
    ]
