# Generated by Django 4.2.4 on 2023-09-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderconfigurator_configurator_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderconfigurator',
            name='configurator_product',
        ),
        migrations.CreateModel(
            name='OrderConfiguratorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderconfigurator')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
