# Generated by Django 4.2.4 on 2023-08-11 11:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productimage_image_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvideo',
            name='title',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
