# Generated by Django 4.2.4 on 2023-12-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeaturepoint',
            name='feature',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productfeaturepoint',
            name='feature_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productfeaturepoint',
            name='feature_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productfeaturepoint',
            name='feature_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='title_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='title_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
