# Generated by Django 4.2.4 on 2023-09-04 05:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_blog_options_alter_productfeature_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='description_uz',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='title_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
