# Generated by Django 4.2.4 on 2024-03-28 08:16

from django.db import migrations, models
import imodels.storage_backends
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_description_title_alter_description_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=imodels.storage_backends.PublicMediaStorage(), upload_to=shop.models.product.product_image_directory_path, verbose_name='Rasm'),
        ),
    ]
