# Generated by Django 4.2.4 on 2023-09-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfigurator',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_configurators', to='shop.orderitem'),
        ),
    ]
