# Generated by Django 4.2.4 on 2024-03-29 03:56

from django.db import migrations, models
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=shop.models.product.product_image_directory_path, verbose_name='Rasm'),
        ),
    ]
