# Generated by Django 4.2.4 on 2023-09-04 19:10

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productvideo_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview_image',
            field=models.ImageField(upload_to=shop.models.blog_image_directory_path),
        ),
    ]
