# Generated by Django 4.2.4 on 2023-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productvideo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_kk',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_uz',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
