# Generated by Django 4.2.4 on 2023-09-04 19:35

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_blog_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=8, validators=[shop.validators.validate_phone_length])),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Просьба связаться',
                'verbose_name_plural': 'Просьбы связаться',
            },
        ),
    ]
