# Generated by Django 4.2.4 on 2023-09-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orderconfigurator_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfiguratoritem',
            name='order_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_conf_items', to='shop.orderconfigurator'),
        ),
    ]
