# Generated by Django 4.2.4 on 2024-03-29 04:40

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', django_quill.fields.QuillField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
