# Generated by Django 4.2.4 on 2023-08-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_title_alter_product_title_kk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_kk',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_kk',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_kk',
            new_name='title_en',
        ),
    ]
