# Generated by Django 4.2.4 on 2023-10-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_blog_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='set_creator',
            new_name='configurator',
        ),
    ]
