# Generated by Django 4.2.4 on 2023-10-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_set_creator_product_configurator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.product'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('product', 'item')},
        ),
    ]
