# Generated by Django 4.2.4 on 2024-07-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
