# Generated by Django 4.2.4 on 2023-09-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_orderconfiguratoritem_order_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuratorcategory',
            name='configurator',
        ),
        migrations.AddField(
            model_name='configuratorproduct',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuratorproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product'),
        ),
    ]
