# Generated by Django 4.2.4 on 2023-09-05 04:40

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[shop.validators.validate_phone_length]),
        ),
    ]
