# Generated by Django 4.2.4 on 2023-09-13 05:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_configuratorcategory_configurator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
