# Generated by Django 4.2.4 on 2024-07-02 04:56

from django.db import migrations, models
import django_quill.fields
import shop.models.blog


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_delete_quillpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(upload_to=shop.models.blog.blog_image_directory_path)),
                ('title', models.CharField(max_length=500)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('text', django_quill.fields.QuillField(blank=True, null=True)),
                ('popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
