# Generated by Django 4.2.4 on 2023-09-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Visible', 'Visible'), ('Invisible', 'Invisible')], default='Visible', max_length=50),
        ),
    ]
