# Generated by Django 4.2.4 on 2023-09-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_blog_created_at_blog_updated_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguratorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configurator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurator', to='shop.configurator')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product')),
            ],
        ),
    ]
