# Generated by Django 4.2.4 on 2023-09-13 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuratorproduct',
            name='conf_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.configuratorcategory'),
        ),
    ]
