# Generated by Django 4.2.4 on 2023-10-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[("To'langan", "To'langan"), ('Kutish', 'Kutish')], default='Kutish', max_length=50),
        ),
    ]
