# Generated by Django 4.2.4 on 2023-08-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_additionaldescription_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='additional_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_description', to='shop.additionaldescription'),
        ),
    ]
