# Generated by Django 4.2.4 on 2023-10-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_configurator',
            field=models.BooleanField(default=False),
        ),
    ]
