# Generated by Django 4.2.4 on 2023-09-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_configuratorproduct_conf_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurator',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='configuratorproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configurator', to='shop.product'),
        ),
    ]
