# Generated by Django 4.2.4 on 2023-09-13 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_configurator_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuratorproduct',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurators', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='configuratorproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.product'),
        ),
    ]
