# Generated by Django 4.2.4 on 2023-10-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_is_configurator'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='configurator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_configurator', to='shop.product'),
        ),
    ]
