# Generated by Django 4.2.4 on 2023-09-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_configuratorproduct_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfiguratorProduct',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='ConfiguratorCategory',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='orderconfigurator',
            name='configurator',
        ),
        migrations.DeleteModel(
            name='Configurator',
        ),
    ]
