# Generated by Django 4.2.4 on 2023-09-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_configurator_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurator',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurators', to='shop.product'),
        ),
    ]
