# Generated by Django 4.2.4 on 2023-09-06 07:04

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_configurator_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurator',
            old_name='title',
            new_name='conf_title',
        ),
        migrations.RemoveField(
            model_name='configurator',
            name='product',
        ),
        migrations.RemoveField(
            model_name='configuratorproduct',
            name='configurator',
        ),
        migrations.AddField(
            model_name='configurator',
            name='conf_image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.configurator_image_directory_path),
        ),
        migrations.CreateModel(
            name='ConfiguratorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('configurator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test', to='shop.configurator')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurators', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='configuratorproduct',
            name='conf_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.configuratorcategory'),
            preserve_default=False,
        ),
    ]
