# Generated by Django 4.2.4 on 2023-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_order_status_delete_orderproductitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[("To'langan", "To'langan"), ('Kutish', 'Kutish'), ('Rad etilgan', 'Rad etilgan')], default='Kutish', max_length=50),
        ),
    ]
