# Generated by Django 4.2.4 on 2023-10-26 10:08

from django.db import migrations, models
import django.db.models.deletion
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_product_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.product.product_gallery_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_galleries', to='shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='DescriptionImage',
        ),
    ]
