# Generated by Django 4.2.4 on 2023-09-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_configuratorcategory_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurator',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configurators', to='shop.product'),
        ),
    ]
