# Generated by Django 4.2.4 on 2023-09-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_configurator_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuratorcategory',
            old_name='title',
            new_name='name',
        ),
    ]
