# Generated by Django 4.2.4 on 2023-10-30 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_productgallery_delete_descriptionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Faqat o'zbek raqamlarigina tasdiqlanadi", regex='^998[0-9]{2}[0-9]{7}$')], verbose_name='Telefon raqam'),
        ),
    ]
