# Generated by Django 4.2.4 on 2023-09-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_rename_title_configuratorcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuratorcategory',
            name='configurator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conf_category', to='shop.configurator'),
        ),
    ]
