# Generated by Django 4.2.4 on 2023-09-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_configuratorcategory_configurator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurator',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configurator', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='configuratorproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
