# Generated by Django 4.2.4 on 2023-09-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_configurator_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_configurator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_own_set', to='shop.product'),
        ),
    ]
