# Generated by Django 4.2.4 on 2023-11-16 05:44

from django.db import migrations, models
import django.db.models.deletion
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='shop.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='configurator',
            field=models.ForeignKey(blank=True, help_text="Mahsulot qaysidir kafiguratorga tegishli bo'lsa kanfigurator ID ni kiriting", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_own_set', to='shop.product', verbose_name='Kanfigurator ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Informatsiya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='information_en',
            field=models.TextField(blank=True, null=True, verbose_name='Informatsiya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='information_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Informatsiya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='information_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Informatsiya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_configurator',
            field=models.BooleanField(default=False, help_text="Agar kanfigurator yaratayotgan bo'lsangir `Ha` ni belgilang", verbose_name='Ushbu mahsulot kanfiguratormi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_by',
            field=models.PositiveIntegerField(default=1, verbose_name='Tartib raqam'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Narx AQSH dollarda (USD)', max_digits=10, null=True, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=shop.models.product.product_image_directory_path, verbose_name='Rasm'),
        ),
    ]
