# Generated by Django 4.2.4 on 2023-11-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_product_category_alter_product_configurator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Naqd', 'Naqd'), ('Payme', 'Payme')], default='Naqd', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Kutish', 'Kutish'), ("To'langan", "To'langan"), ('Rad etilgan', 'Rad etilgan')], default='Kutish', max_length=50),
        ),
    ]
