# Generated by Django 4.2.4 on 2023-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_product_category_alter_product_configurator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ("To'langan", "To'langan"), ('Rad etilgan', 'Rad etilgan')], default='Yangi', max_length=50),
        ),
    ]
