# Generated by Django 4.2.4 on 2023-11-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', '🆕'), ('answered', '✅'), ('rejected', '❌')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ("To'langan", "To'langan"), ('Rad etilgan', 'Rad etilgan'), ('Yetkazib berildi', 'Yetkazib berildi')], default='Yangi', max_length=50),
        ),
    ]
